# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDBELRHgNbnT-oqi_isgOzFfbpOHk033
"""

n, limit = list(map(int, input().split()))
nums = list(map(int, input().split()))
time = 0
people = 0
for i in nums:
  people += i
  time += people
  if people <= limit:
    people = 0
  else:
    people -= limit
time += people
print(time)