# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDBELRHgNbnT-oqi_isgOzFfbpOHk033
"""

n = int(input())
nums = list(map(int, input().split()))
stack = []
answer = [-1]*n
for i in range(n):
  while stack and nums[i] < stack[-1][1]:
    top_ind, top_val = stack.pop()
    answer[top_ind] = i
  stack.append((i, nums[i]))
print(' '.join(map(str, answer)))