# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDBELRHgNbnT-oqi_isgOzFfbpOHk033
"""

everything = list(map(str, input().split()))
stack = []
for i in everything:
  if i.isdigit():
    stack.append(int(i))
  if i == '+':
    first = stack[-2]
    second = stack[-1]
    answer = first + second
    stack.pop()
    stack.pop()
    stack.append(answer)
  if i == '-':
    first = stack[-2]
    second = stack[-1]
    answer = first - second
    stack.pop()
    stack.pop()
    stack.append(answer)
  if i == '*':
    first = stack[-2]
    second = stack[-1]
    answer = first * second
    stack.pop()
    stack.pop()
    stack.append(answer)
  if i == '/':
    first = stack[-2]
    second = stack[-1]
    answer = first / second
    stack.pop()
    stack.pop()
    stack.append(answer)
  if i == '%':
    first = stack[-2]
    second = stack[-1]
    answer = first % second
    stack.pop()
    stack.pop()
    stack.append(answer)
  if i == '//':
    first = stack[-2]
    second = stack[-1]
    answer = first // second
    stack.pop()
    stack.pop()
    stack.append(answer)
print(answer)