# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDBELRHgNbnT-oqi_isgOzFfbpOHk033
"""

n = int(input())
nums = list(map(int, input().split()))
prefixes = [0]*(len(nums) + 1)
for i in range(1, len(nums) + 1):
	prefixes[i] = nums[i-1] + prefixes[i-1]
print(" ".join(map(str, prefixes[1:])))